# Project information
site_name: 'Homelab Playbook'
site_description: 'Documentation to preserve and share knowledge about my homelab.'
site_author: 'Randy Rowland'
site_url: 'https://rowland007.github.io/homelab-playbook/'

# Repository
repo_name: 'Randy Rowland'
repo_url: 'https://github.com/rowland007/'

# Copyright
copyright: 'Copyright &copy; 2021-2023 Randall Rowland<br>This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.'

# Navigation Menu
nav:
    - Overview: 'index.md'
    - Operating Systems:
        'Overview': 'os/index.md'
        'AC-Hunter': 'os/achunter.md'
        'Security Onion': 'os/seconion.md'
    - Applications:
        'Overview': 'apps/index.md'
        'Wazuh': 'apps/wazuh.md'
        'Netbox': 'apps/netbox.md'
        'Kasm': 'apps/kasm.md'
        'WireGuard': 'apps/wireguard.md'
    - Network:
        'Cloudflare DNS': 'network/cloudflare.md'
    - Resources: 
        'Appendix 1': 'resources/app1.md'
        'Website Links': 'resources/websites.md'

# Configuration
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    admonition:
      cite: octicons/link-external-16
    logo: material/file-document-edit-outline

# Customization
extra:
  social:
    - icon: material/cloud
      link: https://randyrowland.me
    - icon: fontawesome/brands/github
      link: https://github.com/rowland007
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/randall-rowland-jr
    - icon: fontawesome/brands/reddit-alien
      link: https://www.reddit.com/user/rowland007

# Extensions
markdown_extensions:
  - abbr
  - pymdownx.critic
  - pymdownx.caret
  - md_in_html
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - tables
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js